name: Unity 版本更新

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建版本目录
        run: |
          mkdir -p public/version

      - name: 下载版本文件
        run: |
          curl -L https://github.com/NoUnityCN/service/releases/download/releases/LTS.json -o public/version/LTS.json
          curl -L https://github.com/NoUnityCN/service/releases/download/releases/TECH.json -o public/version/TECH.json
          curl -L https://github.com/NoUnityCN/service/releases/download/releases/BETA.json -o public/version/BETA.json
          curl -L https://github.com/NoUnityCN/service/releases/download/releases/ALPHA.json -o public/version/ALPHA.json

          echo "已下载的版本文件:"
          ls -la public/version/
          
          echo "LTS版本数量: $(grep -o "unityhub://" public/version/LTS.json | wc -l)"
          echo "TECH版本数量: $(grep -o "unityhub://" public/version/TECH.json | wc -l)"
          echo "BETA版本数量: $(grep -o "unityhub://" public/version/BETA.json | wc -l)"
          echo "ALPHA版本数量: $(grep -o "unityhub://" public/version/ALPHA.json | wc -l)"

      - name: 配置Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: 提交更改
        run: |
          if git diff --quiet public/version/; then
            echo "没有检测到版本更新，跳过提交"
            exit 0
          fi
          git add public/version/
          git commit -m "更新$(date +'%Y-%m-%d') Unity版本数据"

      - name: 推送更改
        run: |
          git push origin HEAD:main